### ISSUE TITLE
swagger.configureSwaggerPaths relevancy?

### ISSUE THREAD

**Issue by codercurtis** [shawngong/Swagger-Node-Express-For-Existing-APIs#1]
Apparently, configureSwaggerPaths is no longer relevant with Swagger 2.0
https://github.com/swagger-api/swagger-node/issues/200

I don't know if it'll break anything or not if you remove it, or even if that code does anything, but just letting you know

**Comment by shawngong** [comment]
Thank you! Sorry this guide has not really been updated in a while, but I will look into it! Leaving it for now as it does not seem to hinder the guide.
