### ISSUE TITLE
Swagger-ui version must be 2.x!!

### ISSUE THREAD

**Issue by nGoline** [shawngong/Swagger-Node-Express-For-Existing-APIs#10]
After a full day trying to make things work with swagger-api I found out that in your instructions you just state that the Swagger-ui must be downloaded from their github page.
It would help a lot if you point out the correct version [swagger-api 2.x](https://github.com/swagger-api/swagger-ui/tree/2.x) so people don't download their latest version - like I did - and render the OAuth2 flow unusable.

**Comment by shawngong** [comment]
@nGoline That is a good point, I'll update the Readme to reflect this
