### ISSUE TITLE
setAppHandler is deprecated

### ISSUE THREAD

**Issue by kevinxh** [shawngong/Swagger-Node-Express-For-Existing-APIs#3]
swagger warns: "setAppHandler is deprecated, pass it to constructor."

**Comment by tebeshir** [comment]
Getting the same error "setAppHandler is deprecated!  Pass it to the constructor instead." and "Not Found" page on http://localhost:8080/v1.

Please help, I am stuck. Any help would be appreciated.

My app.js is attached.
[app.js.docx](https://github.com/shawngong/Swagger-Node-Express-For-Existing-APIs/files/559670/app.js.docx)

**Comment by shawngong** [comment]
Hi, kindly re-examine the guide, it has been updated.

Rather than previously using the `setAppHandler` method, use:

```
var app = express();
var subpath = express();

app.use(bodyParser());
app.use("/v1", subpath);

var swagger = require("swagger-node-express").createNew(subpath);

```
