### ISSUE TITLE
Does this project auto-generates swagger specs for existing express projects?

### ISSUE THREAD

**Issue by rahil471** [shawngong/Swagger-Node-Express-For-Existing-APIs#4]

**Comment by shawngong** [comment]
It does not unfortunately. Is there a way to do that even?

**Comment by jonnycraze** [comment]
I'm also interested in this concept. I had previously started writing my API and now want to get swagger involved. My question is, as i develop addition endpoints, is there something that could compile them into a new json file.

May be a pie in the sky request.

Thanks for this repo and walk through Shawngong, it's very helpful.

**Comment by shawngong** [comment]
@jonnycraze Thanks for the kind words! I am not too up to date with what swagger is doing recently (would love look over it sometime but just been busy), this looks like an okay place to start: https://tech.homeaway.com/development/2016/06/02/generating-swagger-spec.html. I am not even sure if this is possible in swagger (but it would make sense there are some libraries to auto generate swagger-specs out there).

**Comment by rahil471** [comment]
As of now I have included the swagger-ui inside of my express app and exposed it as a static path. So I have all in one place. But again I have to write the specs manually. 
If we ever go by the approach of auto-generating the specs, I guess we can achieve partial success, the biggest challenge would be defining `body` schemas. As nowhere in an express app we have a well defined expected body object.
