### ISSUE TITLE
Swagger route endpoint

### ISSUE THREAD

**Issue by Caspain** [shawngong/Swagger-Node-Express-For-Existing-APIs#6]
Your swagger implementation only maps to localhost home url. I kind of set a home page for that route.
Alternatively i tried setting a separate route for swagger: 
 app.get('/api', function (req, res) {
        res.sendFile(__dirname + '/dist/index.html');
    });
///////////////////////////////////////////////////////////////////////////////////

TOTALY NOT WORKING!
Appreciate any help.

**Comment by shawngong** [comment]
This should work no? Can you upload a fork of my repo with your changes showing this issue? Didn't see one on your profile
