### ISSUE TITLE
setApiInfo() doesn't seem to do anything

### ISSUE THREAD

**Issue by skellertor** [shawngong/Swagger-Node-Express-For-Existing-APIs#7]
I've recreated your steps on my existing express app and I've struggled with getting `setApiInfo()` to actually set the `title, description, etc`.  It seems to just uses the `info` section of the `dist/api-docs.json`.  How do you actually make `setApiInfo()` apply the info?

**Comment by shawngong** [comment]
@skellertor I think setApiInfo may be outdated now? Haven't checked the latest swagger docs, but Swagger uses an info object http://swagger.io/specification/#infoObject, which provides info about the metadata of the project.
