### ISSUE TITLE
Extremely helpful!!! Just one thing missing

### ISSUE THREAD

**Issue by anilyashavant** [shawngong/Swagger-Node-Express-For-Existing-APIs#9]
This is extremely helpful, just one thing...dont use the latest version of Swagger node since the api has changed a bit, and also add the following line which i did not see in the example 
swagger.setAppHandler(app);

Thank you for putting this together

**Comment by shawngong** [comment]
Hi @anilyashavant I believe that setAppHandler has been depreciated on the version of Swagger Node Express that this guide has been updated to!
